var cchoteauensisGroup = L.layerGroup();

markerLib['D57'] = {"Dnum":"D57","state":"CO","county":"Jefferson","age":"Cretaceous","formation":"From white chalk a little above middle of Niobrara formation","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.5","resume":"Baculites, Scaphites sp.","Ifossil":"Clioscaphites choteauensis","collector":"G.R. Scott, W.A. Cobban","date":"10/6/1954","lat":"39.50181","lon":"-105.09565","reference":""};markerLib['D57'].marker = makeMarker(markerLib['D57'].Dnum,markerLib['D57'].lat,markerLib['D57'].lon);cchoteauensisGroup.addLayer(markerLib['D57'].marker);
markerLib['D2665'] = {"Dnum":"D2665","state":"KS","county":"Gove","age":"Cretaceous","formation":"Massive bed of chalk in Smoky Hill member of Niobrara fm.","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.5","resume":"Clioscaphites choteauensis","Ifossil":"Clioscaphites choteauensis","collector":"W. A. Cobban","date":"11/13/1960","lat":"38.79379","lon":"-100.76235","reference":""};markerLib['D2665'].marker = makeMarker(markerLib['D2665'].Dnum,markerLib['D2665'].lat,markerLib['D2665'].lon);cchoteauensisGroup.addLayer(markerLib['D2665'].marker);
markerLib['D2693'] = {"Dnum":"D2693","state":"CO","county":"Pueblo","age":"Cretaceous","formation":"Smoky Hill chalk , Niobrara Fm","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.5","resume":"Inoceramus platinus, Ostrea sp., Baculites sp., Clioscaphites choteauensis","Ifossil":"Clioscaphites choteauensis","collector":"G.R. Scott, W. A. Cobban","date":"12/12/1958","lat":"38.33396","lon":"-104.659","reference":"PP 454-L, I-408"};markerLib['D2693'].marker = makeMarker(markerLib['D2693'].Dnum,markerLib['D2693'].lat,markerLib['D2693'].lon);cchoteauensisGroup.addLayer(markerLib['D2693'].marker);
markerLib['D3501'] = {"Dnum":"D3501","state":"CO","county":"Pueblo","age":"Cretaceous","formation":"Smoky Hill shale member. Niobrara fm.","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.5","resume":"Inoceramus platinus?, Ostrea sp., Baculites, Clioscaphites choteauensis, Inoceramus ","Ifossil":"Clioscaphites choteauensis","collector":"W. A Coban and G.R. Scott ","date":"8/31/61; 10/11/61","lat":"38.32035","lon":"-104.65809","reference":"PP 454-L, Bull 1262, I-408, Acta Geologia Polonica 56, 3  241-348"};markerLib['D3501'].marker = makeMarker(markerLib['D3501'].Dnum,markerLib['D3501'].lat,markerLib['D3501'].lon);cchoteauensisGroup.addLayer(markerLib['D3501'].marker);
markerLib['D3503'] = {"Dnum":"D3503","state":"CO","county":"Pueblo","age":"Cretaceous","formation":"Smoky Hill shale member. Niobrara fm.","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.5","resume":"Inoceramus platinus, Clioscaphites choteauensis","Ifossil":"Clioscaphites choteauensis","collector":"G.R. Scott","date":"8/17/1961","lat":"38.3144","lon":"-104.65875","reference":"PP 454-L, Bull 1262, I-408, Acta Geologia Polonica 56, 3  241-348"};markerLib['D3503'].marker = makeMarker(markerLib['D3503'].Dnum,markerLib['D3503'].lat,markerLib['D3503'].lon);cchoteauensisGroup.addLayer(markerLib['D3503'].marker);
markerLib['D3504'] = {"Dnum":"D3504","state":"CO","county":"Pueblo","age":"Cretaceous","formation":"Smoky Hill shale member. Niobrara fm.","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.5","resume":"Inoceramus platinus, Clioscaphites choteauensis, Ostrea congesta","Ifossil":"Clioscaphites choteauensis","collector":"G.R. Scott","date":"8/31/1961","lat":"38.31566","lon":"-104.65794","reference":"PP 454-L, Bull 1262, I-408, Acta Geologia Polonica 56, 3  241-348"};markerLib['D3504'].marker = makeMarker(markerLib['D3504'].Dnum,markerLib['D3504'].lat,markerLib['D3504'].lon);cchoteauensisGroup.addLayer(markerLib['D3504'].marker);
markerLib['D4176'] = {"Dnum":"D4176","state":"MT","county":"Meagher","age":"Cretaceous","formation":"Lower part of Telegraph Creek Formation but higher than D4175","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.5","resume":"Inoceramus platinus Logan, Ostrea sp., Baculites cf. B. asper Morton, Clioscaphites choteauensis Cobban?","Ifossil":"Clioscaphites choteauensis","collector":"J. R. Gill, W. A. Cobban","date":"7/19/1962","lat":"46.3686","lon":"-110.6303","reference":""};markerLib['D4176'].marker = makeMarker(markerLib['D4176'].Dnum,markerLib['D4176'].lat,markerLib['D4176'].lon);cchoteauensisGroup.addLayer(markerLib['D4176'].marker);
markerLib['D5141'] = {"Dnum":"D5141","state":"KS","county":"Logan","age":"Cretaceous","formation":"Smoky Hill Member of Niobrara Formation","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.5","resume":"Clioscaphites choteauensis","Ifossil":"Clioscaphites choteauensis","collector":"W. A. Cobban","date":"6/17/65, 11/8/65","lat":"38.80449","lon":"-100.94183","reference":""};markerLib['D5141'].marker = makeMarker(markerLib['D5141'].Dnum,markerLib['D5141'].lat,markerLib['D5141'].lon);cchoteauensisGroup.addLayer(markerLib['D5141'].marker);
markerLib['D5443'] = {"Dnum":"D5443","state":"CO","county":"Routt","age":"Cretaceous","formation":"Niobrara Formation ","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.5","resume":"Ostrea sp., Clioscaphites choteauensis Cobban","Ifossil":"Clioscaphites choteauensis","collector":"George L. Snyder","date":"1966","lat":"40.53162","lon":"-106.91967","reference":""};markerLib['D5443'].marker = makeMarker(markerLib['D5443'].Dnum,markerLib['D5443'].lat,markerLib['D5443'].lon);cchoteauensisGroup.addLayer(markerLib['D5443'].marker);
markerLib['D7322'] = {"Dnum":"D7322","state":"NM","county":"Santa Fe","age":"Cretaceous","formation":"Mancos Shale ","member":"","stage":"Coniacian","substage":"Lower","ageDate":"88.76","resume":"Stantonoceras, Clioscaphites choteauensis; Inoceramus platinus","Ifossil":"Clioscaphites choteauensis","collector":"G.R. Scott, Juanita Scott ","date":"4/15/1970","lat":"35.4936","lon":"-106.181","reference":""};markerLib['D7322'].marker = makeMarker(markerLib['D7322'].Dnum,markerLib['D7322'].lat,markerLib['D7322'].lon);cchoteauensisGroup.addLayer(markerLib['D7322'].marker);
markerLib['D9394'] = {"Dnum":"D9394","state":"CO","county":"Routt","age":"Cretaceous","formation":"Niobrara Fm., Smokey Hill Member","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.5","resume":"Clioscaphites choteauensis Cobban","Ifossil":"Clioscaphites choteauensis","collector":"G.L. Snyder","date":"1975","lat":"40.31952","lon":"-106.94426","reference":""};markerLib['D9394'].marker = makeMarker(markerLib['D9394'].Dnum,markerLib['D9394'].lat,markerLib['D9394'].lon);cchoteauensisGroup.addLayer(markerLib['D9394'].marker);
markerLib['D9864'] = {"Dnum":"D9864","state":"UT","county":"Wayne","age":"Cretaceous","formation":"Mancos Shale, 563 ft above base of Blue Gate Member, ","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.5","resume":"Clioscaphites choteauensis Cobban","Ifossil":"Clioscaphites choteauensis","collector":"B.E. Law ","date":"1976","lat":"38.3469","lon":"-110.982","reference":""};markerLib['D9864'].marker = makeMarker(markerLib['D9864'].Dnum,markerLib['D9864'].lat,markerLib['D9864'].lon);cchoteauensisGroup.addLayer(markerLib['D9864'].marker);
markerLib['D11386'] = {"Dnum":"D11386","state":"NM","county":"Colfax","age":"Cretaceous","formation":"Niobrara Formation, from a 10&quot; gray limestone concretions ledge","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.5","resume":"Clioscaphites choteauensis ","Ifossil":"Clioscaphites choteauensis","collector":"Scott","date":"9/15/1980","lat":"36.575","lon":"-104.5238","reference":""};markerLib['D11386'].marker = makeMarker(markerLib['D11386'].Dnum,markerLib['D11386'].lat,markerLib['D11386'].lon);cchoteauensisGroup.addLayer(markerLib['D11386'].marker);
markerLib['D12195'] = {"Dnum":"D12195","state":"MT","county":"Wheatland","age":"Cretaceous","formation":"Colorado Shale","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.5","resume":"Clioscaphites choteauensis ","Ifossil":"Clioscaphites choteauensis","collector":"J. Warne","date":"1966","lat":"46.52025","lon":"-110.12362","reference":""};markerLib['D12195'].marker = makeMarker(markerLib['D12195'].Dnum,markerLib['D12195'].lat,markerLib['D12195'].lon);cchoteauensisGroup.addLayer(markerLib['D12195'].marker);
markerLib['D12198'] = {"Dnum":"D12198","state":"KS","county":"Rooks","age":"Cretaceous","formation":"Smoky Hill Formation ","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.5","resume":"Clioscaphites choteauensis ","Ifossil":"Clioscaphites choteauensis","collector":"M. V. Walker","date":"1966","lat":"39.54628","lon":"-99.59344","reference":""};markerLib['D12198'].marker = makeMarker(markerLib['D12198'].Dnum,markerLib['D12198'].lat,markerLib['D12198'].lon);cchoteauensisGroup.addLayer(markerLib['D12198'].marker);
markerLib['D12404'] = {"Dnum":"D12404","state":"CO","county":"Larimer","age":"Cretaceous","formation":"Niobrara Formation, from middle limestone unit of Smoky Hill Member","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.5","resume":"Ostrea sp, Clioscaphites choteauensis Cobban","Ifossil":"Clioscaphites choteauensis","collector":"Scott","date":"10/25/1983","lat":"40.82189","lon":"-105.1394","reference":""};markerLib['D12404'].marker = makeMarker(markerLib['D12404'].Dnum,markerLib['D12404'].lat,markerLib['D12404'].lon);cchoteauensisGroup.addLayer(markerLib['D12404'].marker);
markerLib['D13275'] = {"Dnum":"D13275","state":"UT","county":"Grand","age":"Cretaceous","formation":"Mancos Shale, from  l&apos; thick orange limestone bed 40&apos; above D13274","member":"","stage":"Santonian","substage":"Upper","ageDate":"85","resume":"Clioscaphites chotoauensis","Ifossil":"Clioscaphites choteauensis","collector":"Cobban","date":"5/7/1992","lat":"39.0323","lon":"-110.13722","reference":""};markerLib['D13275'].marker = makeMarker(markerLib['D13275'].Dnum,markerLib['D13275'].lat,markerLib['D13275'].lon);cchoteauensisGroup.addLayer(markerLib['D13275'].marker);
markerLib['D13391'] = {"Dnum":"D13391","state":"CO","county":"Pueblo","age":"Cretaceous","formation":"Niobrara Formation, top of middle chalk ","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.5","resume":"Clioscaphites choteauensis ","Ifossil":"Clioscaphites choteauensis","collector":"Cobban","date":"3/23/1993","lat":"38.31973","lon":"-104.66217","reference":""};markerLib['D13391'].marker = makeMarker(markerLib['D13391'].Dnum,markerLib['D13391'].lat,markerLib['D13391'].lon);cchoteauensisGroup.addLayer(markerLib['D13391'].marker);
markerLib['D14093'] = {"Dnum":"D14093","state":"MT","county":"Toole","age":"Cretaceous","formation":"Marias River Shale, Kevin Member, 68&apos; above a 3-inch-thick bentonite","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.5","resume":"Clioscaphites choteauensis","Ifossil":"Clioscaphites choteauensis","collector":"Cobban","date":"1996","lat":"48.45095","lon":"-112.10757","reference":""};markerLib['D14093'].marker = makeMarker(markerLib['D14093'].Dnum,markerLib['D14093'].lat,markerLib['D14093'].lon);cchoteauensisGroup.addLayer(markerLib['D14093'].marker);
markerLib['D4371'] = {"Dnum":"D4371","state":"MT","county":"Carbon","age":"Cretaceous","formation":"Colorado Shale, 290&apos; below top.","member":"","stage":"Santonian","substage":"Middle","ageDate":"85.1284","resume":"Inoceramus bueltenensis","Ifossil":"Clioscaphites choteauensis bueltenensis","collector":"Keith Yenn","date":"1963","lat":"45.6031","lon":"-108.9211","reference":"Acta Geologia Polonica 56, 3  241-348"};markerLib['D4371'].marker = makeMarker(markerLib['D4371'].Dnum,markerLib['D4371'].lat,markerLib['D4371'].lon);cchoteauensisGroup.addLayer(markerLib['D4371'].marker);

shoreLib['cchoteauensis'].initInfo = 'D4371'
shoreLib['cchoteauensis'].markers=cchoteauensisGroup;