var csaxitonianusGroup = L.layerGroup();

markerLib['D3491'] = {"Dnum":"D3491","state":"CO","county":"Pueblo","age":"Cretaceous","formation":"Smoky Hill shale member. Niobrara fm.","member":"","stage":"Santonian","substage":"Lower","ageDate":"85.3","resume":"Inoceramus undulaptoplicatus, Pteria sp., Ostrea sp., Baculites codyensis, Clioscaphites saxitonianus","Ifossil":"Clioscaphites saxitonianus","collector":"G.R. Scott","date":"8/24/1961","lat":"38.29585","lon":"-104.67874","reference":"PP 454-L, Bull 1262, I-408, Acta Geologia Polonica 56, 3  241-348"};markerLib['D3491'].marker = makeMarker(markerLib['D3491'].Dnum,markerLib['D3491'].lat,markerLib['D3491'].lon);csaxitonianusGroup.addLayer(markerLib['D3491'].marker);
markerLib['D7235'] = {"Dnum":"D7235","state":"UT","county":"Emery","age":"Cretaceous","formation":"Mancos Shale","member":", from brown-weathering ss concretions 100' below base of Emery SS Mbr","stage":"Santonian","substage":"Lower","ageDate":"85.3","resume":"Clioscaphites saxitonianus (McLearn)","Ifossil":"Clioscaphites saxitonianus","collector":"Gill, Blanchard, Cobban","date":"1969","lat":"39.08088","lon":"-111.17894","reference":""};markerLib['D7235'].marker = makeMarker(markerLib['D7235'].Dnum,markerLib['D7235'].lat,markerLib['D7235'].lon);csaxitonianusGroup.addLayer(markerLib['D7235'].marker);
markerLib['D7320'] = {"Dnum":"D7320","state":"NM","county":"Santa Fe","age":"Cretaceous","formation":"Mancos Shale ","member":"","stage":"Santonian","substage":"Lower","ageDate":"85.3","resume":"Stantonoceras","Ifossil":"Clioscaphites saxitonianus","collector":"G.R. Scott, Juanita Scott ","date":"4/14/1970","lat":"35.4562","lon":"-105.9035","reference":""};markerLib['D7320'].marker = makeMarker(markerLib['D7320'].Dnum,markerLib['D7320'].lat,markerLib['D7320'].lon);csaxitonianusGroup.addLayer(markerLib['D7320'].marker);
markerLib['D8288'] = {"Dnum":"D8288","state":"MT ","county":"Teton","age":"Cretaceous","formation":"Marias River Formation ","member":"","stage":"Santonian","substage":"Lower","ageDate":"86.8","resume":"Clioscaphites saxitonianus (MacLearn) ","Ifossil":"Clioscaphites saxitonianus","collector":"M. R. Mudge, R. L. Earhart ","date":"1969","lat":"47.86177","lon":"-112.9289","reference":""};markerLib['D8288'].marker = makeMarker(markerLib['D8288'].Dnum,markerLib['D8288'].lat,markerLib['D8288'].lon);csaxitonianusGroup.addLayer(markerLib['D8288'].marker);
markerLib['D11304'] = {"Dnum":"D11304","state":"NM","county":"Colfax","age":"Cretaceous","formation":"Niobrara Formation ","member":"","stage":"Santonian","substage":"Lower","ageDate":"85.3","resume":"Inoceramus undulatoplicatus ","Ifossil":"Clioscaphites saxitonianus","collector":"G.R. Scott ","date":"8/23/1980","lat":"36.5325","lon":"-104.5322","reference":""};markerLib['D11304'].marker = makeMarker(markerLib['D11304'].Dnum,markerLib['D11304'].lat,markerLib['D11304'].lon);csaxitonianusGroup.addLayer(markerLib['D11304'].marker);
markerLib['D12194'] = {"Dnum":"D12194","state":"NM","county":"Santa Fe ","age":"Cretaceous","formation":"Mancos Shale ","member":"","stage":"Santonian","substage":"Lower","ageDate":"86.8","resume":"Clioscaphites saxitonianus?","Ifossil":"Clioscaphites saxitonianus","collector":"C. E. Stearns","date":"","lat":"35.42004","lon":"-105.91062","reference":""};markerLib['D12194'].marker = makeMarker(markerLib['D12194'].Dnum,markerLib['D12194'].lat,markerLib['D12194'].lon);csaxitonianusGroup.addLayer(markerLib['D12194'].marker);
markerLib['D12685'] = {"Dnum":"D12685","state":"NM","county":"Santa Fe","age":"Cretaceous","formation":"Mancos Shale ","member":"","stage":"Santonian","substage":"Lower","ageDate":"85.3","resume":"Clioscaphites saxitonianus ","Ifossil":"Clioscaphites saxitonianus","collector":"Shell Oil - R. Carlson, J. Smallwood","date":"1959","lat":"35.42979","lon":"-105.90976","reference":""};markerLib['D12685'].marker = makeMarker(markerLib['D12685'].Dnum,markerLib['D12685'].lat,markerLib['D12685'].lon);csaxitonianusGroup.addLayer(markerLib['D12685'].marker);
markerLib['D12898'] = {"Dnum":"D12898","state":"MT","county":"Madison","age":"Cretaceous","formation":"Cody Shale","member":"","stage":"Santonian","substage":"Lower","ageDate":"86.8","resume":"Inoceramus sp, Scaphites depressus Reeside, Clioscaphites saxitonianus (McLearn) ","Ifossil":"Clioscaphites saxitonianus","collector":"R. G. Tysdal","date":"1987","lat":"45.25661","lon":"-111.48063","reference":""};markerLib['D12898'].marker = makeMarker(markerLib['D12898'].Dnum,markerLib['D12898'].lat,markerLib['D12898'].lon);csaxitonianusGroup.addLayer(markerLib['D12898'].marker);
markerLib['D14130'] = {"Dnum":"D14130","state":"NM","county":"Santa Fe","age":"Cretaceous","formation":"From a sandy unit with sandy calcareous concretions and brown silty calcareous concretions about same stratigraphic level as D14128","member":"","stage":"Santonian","substage":"Lower","ageDate":"86.8","resume":"Clioscaphites saxitonianus (McLearn), Cordiceramus pontoni (McLearn), Cyprimeria sp., Baculites codyensis Reeside","Ifossil":"Clioscaphites saxitonianus","collector":"Layman, Sawyer and Cobban","date":"2001","lat":"35.42168","lon":"-105.89991","reference":""};markerLib['D14130'].marker = makeMarker(markerLib['D14130'].Dnum,markerLib['D14130'].lat,markerLib['D14130'].lon);csaxitonianusGroup.addLayer(markerLib['D14130'].marker);
markerLib['D14131'] = {"Dnum":"D14131","state":"NM","county":"Santa Fe","age":"Cretaceous","formation":"Mancos Shale, from unit with gray and tan calcareous concretions","member":"","stage":"Santonian","substage":"Lower","ageDate":"85.3","resume":"Clioscaphites saxitonianus (McLearn), Pteria sp., Cladiceramus undulatoplicatus (Roemer), Placenticeras, Baculites codyensis Reeside, ","Ifossil":"Clioscaphites saxitonianus","collector":"Layman, Sawyer and Cobban","date":"2001","lat":"35.40122","lon":"-105.92429","reference":""};markerLib['D14131'].marker = makeMarker(markerLib['D14131'].Dnum,markerLib['D14131'].lat,markerLib['D14131'].lon);csaxitonianusGroup.addLayer(markerLib['D14131'].marker);
markerLib['D14305'] = {"Dnum":"D14305","state":"NM","county":"Rio Arriba","age":"Cretaceous","formation":"Lewis Shale","member":"","stage":"Campanian","substage":"Middle","ageDate":"78","resume":"Baculites gregoryensis","Ifossil":"Clioscaphites saxitonianus","collector":"J. Fasset","date":"2003","lat":"36.22906","lon":"-106.95019","reference":""};markerLib['D14305'].marker = makeMarker(markerLib['D14305'].Dnum,markerLib['D14305'].lat,markerLib['D14305'].lon);csaxitonianusGroup.addLayer(markerLib['D14305'].marker);
markerLib['D11276'] = {"Dnum":"D11276","state":"MT","county":"Madison","age":"Cretaceous","formation":"From sandy mudstone 40 - 90 m above base of section","member":"","stage":"Santonian","substage":"Lower","ageDate":"87","resume":"Inoceramus stantoni Sokolow, Volviceramus sp, Pseudoperna congesta (Conrad), Scaphites cf. S. depressus Reeside, Clioscaphites saxitonianus (McLearn) ","Ifossil":"Clioscaphites saxitonianus, Magadiceramus subquadratus","collector":"R. G. Tysdal","date":"1980","lat":"45.25915","lon":"-111.47828","reference":"Bull 1949"};markerLib['D11276'].marker = makeMarker(markerLib['D11276'].Dnum,markerLib['D11276'].lat,markerLib['D11276'].lon);csaxitonianusGroup.addLayer(markerLib['D11276'].marker);
markerLib['D12896'] = {"Dnum":"D12896","state":"MT","county":"Madison","age":"Cretaceous","formation":"Cody Shale","member":"","stage":"Santonian","substage":"Upper ","ageDate":"85.308714","resume":"Inoceramus stantoni Sokolow, Clioscaphites saxitonianus (MacLearn) ","Ifossil":"Clioscaphites saxitonianus, Magadiceramus subquadratus","collector":"R. G. Tysdal","date":"1987","lat":"45.25661","lon":"-111.48063","reference":""};markerLib['D12896'].marker = makeMarker(markerLib['D12896'].Dnum,markerLib['D12896'].lat,markerLib['D12896'].lon);csaxitonianusGroup.addLayer(markerLib['D12896'].marker);

shoreLib['csaxitonianus'].initInfo = 'D12896'
shoreLib['csaxitonianus'].markers=csaxitonianusGroup;