var dbassleriGroup = L.layerGroup();

markerLib['D666'] = {"Dnum":"D666","state":"MT","county":"Toole","age":"Cretaceous","formation":"Telegraph Creek formation ,105 feet above base. ","member":"","stage":"Santonian","substage":"Upper","ageDate":"83.88","resume":"Inoceramus lobatus  Ostrea congesta,  Desmoscaphites bassleri","Ifossil":"Desmoscaphites bassleri","collector":"B.R. Alto","date":"1955","lat":"48.4889","lon":"-112.0537","reference":"PP 450 D, Acta Geologia Polonica 56, 3  241-348"};markerLib['D666'].marker = makeMarker(markerLib['D666'].Dnum,markerLib['D666'].lat,markerLib['D666'].lon);dbassleriGroup.addLayer(markerLib['D666'].marker);
markerLib['D688'] = {"Dnum":"D688","state":"MT","county":"Toole","age":"Cretaceous","formation":"Marias River Shale. Colorado shale ,about 5 feet below top .","member":"","stage":"Santonian","substage":"Upper","ageDate":"84.2","resume":"Baculites sp ., Desmoscaphtes erdmanni, Crinoid -fragments of arms , Uintacrinus socialis Grinnell","Ifossil":"Desmoscaphites bassleri","collector":"C.E. Erdmann","date":"August 1955","lat":"48.49203","lon":"-111.3928","reference":"PP 450 D, Bull 2113"};markerLib['D688'].marker = makeMarker(markerLib['D688'].Dnum,markerLib['D688'].lat,markerLib['D688'].lon);dbassleriGroup.addLayer(markerLib['D688'].marker);
markerLib['D937'] = {"Dnum":"D937","state":"MT","county":"Glacier","age":"Cretaceous","formation":"Pierre shale","member":"Virgelle sandstone ","stage":"Santonian","substage":"Upper","ageDate":"83.88","resume":"Ostrea sp., Desmoscaphites bassleri.","Ifossil":"Desmoscaphites bassleri","collector":"B.R. Alto","date":"        June,1956","lat":"48.50621","lon":"-113.10229","reference":"PP 450 D"};markerLib['D937'].marker = makeMarker(markerLib['D937'].Dnum,markerLib['D937'].lat,markerLib['D937'].lon);dbassleriGroup.addLayer(markerLib['D937'].marker);
markerLib['D972'] = {"Dnum":"D972","state":"MT","county":"Blaine","age":"Cretaceous","formation":"","member":"","stage":"Santonian","substage":"Upper","ageDate":"83.88","resume":"Nemodon n. sp., Inoceramus labatus Goldfuss, Pteria linguaeformis (Evans and Shumard), Pleuromya sp., Baculites sp., Desmoscaphites bassleri","Ifossil":"Desmoscaphites bassleri","collector":"W.T.Pecora  ","date":"1954","lat":"48.21673","lon":"-109.36779","reference":""};markerLib['D972'].marker = makeMarker(markerLib['D972'].Dnum,markerLib['D972'].lat,markerLib['D972'].lon);dbassleriGroup.addLayer(markerLib['D972'].marker);
markerLib['D2509'] = {"Dnum":"D2509","state":"UT","county":"Carbon","age":"Cretaceous","formation":"From orange-brown calcareous sandstone concretions in lowest of 3 sandstones of Emery sandstone member of Mancos shale.","member":"","stage":"Santonian","substage":"Upper","ageDate":"83.88","resume":"Inoceramus cf. I. balticus Boehm, Desmoscaphites bassleri Reeside, Placenticeras cf. P. quadalupae Roemer","Ifossil":"Desmoscaphites bassleri","collector":"A. D. Zapp, W. A. Cobban","date":"5/10/1960","lat":"39.66906","lon":"-110.83793","reference":"PP 450 D"};markerLib['D2509'].marker = makeMarker(markerLib['D2509'].Dnum,markerLib['D2509'].lat,markerLib['D2509'].lon);dbassleriGroup.addLayer(markerLib['D2509'].marker);
markerLib['D4192'] = {"Dnum":"D4192","state":"WY","county":"Big Horn","age":"Cretaceous","formation":"Cody Shale, 1,580 feet above base (10 feet above top of Niobrara Member)","member":"","stage":"Santonian","substage":"Upper","ageDate":"83.88","resume":"Desmoscaphites? Sp","Ifossil":"Desmoscaphites bassleri","collector":"J. R. Gill, R. Vaughn","date":"1962","lat":"44.67067","lon":"-108.29404","reference":""};markerLib['D4192'].marker = makeMarker(markerLib['D4192'].Dnum,markerLib['D4192'].lat,markerLib['D4192'].lon);dbassleriGroup.addLayer(markerLib['D4192'].marker);
markerLib['D4912'] = {"Dnum":"D4912","state":"MT","county":"Petroleum","age":"Cretaceous","formation":"Telegraph Creek Fm. From gray limestone concretions.","member":"","stage":"Santonian","substage":"Upper","ageDate":"81.32843","resume":"Desmoscaphites, Baculites thomi, Desmoscaphites bassleri, Inoceramus cf. brancoiformis, Ostrea sp.","Ifossil":"Desmoscaphites bassleri","collector":"W. A. Cobban","date":"7/31/1965","lat":"47.004366","lon":"-108.337408","reference":""};markerLib['D4912'].marker = makeMarker(markerLib['D4912'].Dnum,markerLib['D4912'].lat,markerLib['D4912'].lon);dbassleriGroup.addLayer(markerLib['D4912'].marker);
//markerLib['D11366'] = {"Dnum":"D11366","state":"NM","county":"Socorro","age":"Cretaceous","formation":"D - Cross Shale, float below D10604 and above D10466","member":"","stage":"Santonian","substage":"Upper","ageDate":"83.88","resume":"Cameleolopha lugubris -extremely large specimens","Ifossil":"Desmoscaphites bassleri","collector":"Hook","date":"12/4/1980","lat":"33.88083","lon":"-106.75408","reference":""};markerLib['D11366'].marker = makeMarker(markerLib['D11366'].Dnum,markerLib['D11366'].lat,markerLib['D11366'].lon);dbassleriGroup.addLayer(markerLib['D11366'].marker);
markerLib['D11388'] = {"Dnum":"D11388","state":"NM","county":"Colfax","age":"Cretaceous","formation":"Niobrara Formation, from limestone concretions in platy shale","member":"","stage":"Santonian","substage":"Upper","ageDate":"83.91","resume":"Desmoscaphites bassleri","Ifossil":"Desmoscaphites bassleri","collector":"G.R. Scott ","date":"9/16/1980","lat":"36.5884","lon":"-104.5323","reference":""};markerLib['D11388'].marker = makeMarker(markerLib['D11388'].Dnum,markerLib['D11388'].lat,markerLib['D11388'].lon);dbassleriGroup.addLayer(markerLib['D11388'].marker);
markerLib['D13036'] = {"Dnum":"D13036","state":"UT","county":"Emery","age":"Cretaceous","formation":"Mancos Shale, from silty flaggy ss unit that ls channelad at base","member":"","stage":"Santonian","substage":"Upper","ageDate":"83.88","resume":"Desmoscaphites bassleri","Ifossil":"Desmoscaphites bassleri","collector":"T. D. Fouch, Chris Shaw, and cobban","date":"1/8/1988","lat":"39.25198","lon":"-110.31003","reference":""};markerLib['D13036'].marker = makeMarker(markerLib['D13036'].Dnum,markerLib['D13036'].lat,markerLib['D13036'].lon);dbassleriGroup.addLayer(markerLib['D13036'].marker);
markerLib['D14354'] = {"Dnum":"D14354","state":"CO","county":"Montezuma","age":"Cretaceous","formation":"Mancos Shale","member":", 1065' below base of Point Lookout Sandstone","stage":"Santonian","substage":"Upper","ageDate":"84.3","resume":"Desmoscaphites bassleri","Ifossil":"Desmoscaphites bassleri","collector":"W.S. Pike, Jr.","date":"1933 or 34'","lat":"37.32501","lon":"-108.41587","reference":""};markerLib['D14354'].marker = makeMarker(markerLib['D14354'].Dnum,markerLib['D14354'].lat,markerLib['D14354'].lon);dbassleriGroup.addLayer(markerLib['D14354'].marker);
markerLib['D14355'] = {"Dnum":"D14355","state":"CO","county":"Montezuma","age":"Cretaceous","formation":"Mancos Shale ","member":"815' below Point Lookout Ss.","stage":"Santonian","substage":"Upper","ageDate":"84.3","resume":"Desmoscaphites bassleri","Ifossil":"Desmoscaphites bassleri","collector":"W.S. Pike, Jr.","date":"1933 or 34'","lat":"37.32501","lon":"-108.41587","reference":""};markerLib['D14355'].marker = makeMarker(markerLib['D14355'].Dnum,markerLib['D14355'].lat,markerLib['D14355'].lon);dbassleriGroup.addLayer(markerLib['D14355'].marker);
markerLib['D5706'] = {"Dnum":"D5706","state":"NM","county":"Rio Arriba","age":"Cretaceous","formation":"Telegraph Creek formation, below conspicuous cliff of thin-bedded sandstone","member":"","stage":"Santonian","substage":"Upper","ageDate":"83.91","resume":"Ostrea sp., Baculites sp., Desmoscaphites bassleri Reeside?","Ifossil":"Desmoscaphites bassleri ","collector":"Gill & Cobban","date":"7/13/1966","lat":"36.4211","lon":"-106.8349","reference":""};markerLib['D5706'].marker = makeMarker(markerLib['D5706'].Dnum,markerLib['D5706'].lat,markerLib['D5706'].lon);dbassleriGroup.addLayer(markerLib['D5706'].marker);
markerLib['D4280'] = {"Dnum":"D4280","state":"MT","county":"Yellowstone","age":"Cretaceous","formation":"From gray silty limestone concretion in ridge - forming sandy unit, 43 feet above base of Telegraph Creek Formation","member":"","stage":"Santonian","substage":"Upper","ageDate":"83.88","resume":"Inoceramus cf. I. patootensis de Loriol, Pteria sp., Ostrea sp.,  Baculites haresi Reeside, Haresiceras mancosense, Inoceramus sp., Baculites cf. asper, Desmoscaphites bassleri, Scaphites leei, Inoceramus patootensis, corbulid","Ifossil":"Desmoscaphites bassleri, Cordiceramus meulleri","collector":"Gill, Burkholder, Cobban","date":"9/11/1963","lat":"45.6815","lon":"-108.1693","reference":"PP 619"};markerLib['D4280'].marker = makeMarker(markerLib['D4280'].Dnum,markerLib['D4280'].lat,markerLib['D4280'].lon);dbassleriGroup.addLayer(markerLib['D4280'].marker);
markerLib['D4705'] = {"Dnum":"D4705","state":"WY","county":"Hot Springs","age":"Cretaceous","formation":"Cody Shale, 1,000 ft below top.","member":"","stage":"Santonian","substage":"Upper","ageDate":"83.88","resume":"Inoceramus patootensis de Loriol, Desmoscaphites bassleri Reeside","Ifossil":"Desmoscaphites bassleri, Cordiceramus meulleri","collector":"J. R. Gill","date":"1964","lat":"44.0669","lon":"-108.7908","reference":""};markerLib['D4705'].marker = makeMarker(markerLib['D4705'].Dnum,markerLib['D4705'].lat,markerLib['D4705'].lon);dbassleriGroup.addLayer(markerLib['D4705'].marker);
markerLib['D1128'] = {"Dnum":"D1128","state":"MT","county":"Teton","age":"Cretaceous","formation":"Telegraph Creek formtion ,64,8 feet from top of unit 1, sec .5.","member":"","stage":"Santonian","substage":"Upper","ageDate":"83.88","resume":"Inoceramus sp., Ostrea congesta, Baculite haresi, Desmoscaphites bassleri.","Ifossil":"Desmoscaphites bassleri.","collector":"M.R.Mudge , J.J.Halbert","date":"7/29/1956","lat":"47.62697","lon":"-112.64142","reference":"PP 450 D"};markerLib['D1128'].marker = makeMarker(markerLib['D1128'].Dnum,markerLib['D1128'].lat,markerLib['D1128'].lon);dbassleriGroup.addLayer(markerLib['D1128'].marker);

shoreLib['dbassleri'].initInfo = 'D1128';
shoreLib['dbassleri'].markers=dbassleriGroup;