var pgermari_quadratusGroup = L.layerGroup();

markerLib['D13199'] = {"Dnum":"D13199","state":"MT","county":"Yellowstone","age":"Cretaceous","formation":"Turner Member, from upper  6 ","member":"","stage":"Turonian","substage":"Upper","ageDate":"89.8","resume":"Prionocyclus germani, Scaphites nigricollensis","Ifossil":"Prionocyclus germani","collector":"Cobban","date":"7/28/1991","lat":"45.70817","lon":"-108.56229","reference":""};markerLib['D13199'].marker = makeMarker(markerLib['D13199'].Dnum,markerLib['D13199'].lat,markerLib['D13199'].lon);pgermari_quadratusGroup.addLayer(markerLib['D13199'].marker);
markerLib['D13309'] = {"Dnum":"D13309","state":"NM","county":"McKinley","age":"Cretaceous","formation":"Mancos Shale, from dark-gray shale unit containing red ironestone concretions about 20 ft above D13308 and 85 ft below base of main Gallup Sandstone ","member":"","stage":"Turonian","substage":"Upper","ageDate":"88.8","resume":"Nuculana sp, Inoceramus incertus Jimbo, Pleuriocardia pauperculum (Meek), Placenticeras pseudoplacenta Hyatt, Prionocyclus germari (Reuss), Baculites yokoyamai Tokunaga and Shimizu ","Ifossil":"Prionocyclus germani","collector":"Jacques F. Robertson and Cobban","date":"6/22/1992","lat":"35.55056","lon":"-108.17611","reference":""};markerLib['D13309'].marker = makeMarker(markerLib['D13309'].Dnum,markerLib['D13309'].lat,markerLib['D13309'].lon);pgermari_quadratusGroup.addLayer(markerLib['D13309'].marker);
markerLib['D13311'] = {"Dnum":"D13311","state":"NM","county":"McKinley","age":"Cretaceous","formation":"Mancos Shale ","member":"","stage":"Turonian","substage":"Upper","ageDate":"88.8","resume":"Prionocyclus germari","Ifossil":"Prionocyclus germani","collector":"C. M. Molenaar","date":"1992","lat":"35.47684","lon":"-107.84731","reference":"OC-143"};markerLib['D13311'].marker = makeMarker(markerLib['D13311'].Dnum,markerLib['D13311'].lat,markerLib['D13311'].lon);pgermari_quadratusGroup.addLayer(markerLib['D13311'].marker);
markerLib['D9118'] = {"Dnum":"D9118","state":"WY","county":"Natrona","age":"Cretaceous","formation":"Frontier Formation","member":"Wall Creek Mbr. from uppermost sandstone ","stage":"Turonian","substage":"Upper","ageDate":"88.8","resume":"Nuculana sp, Phelopteria sp, Inoceramus cf. I. incertus Jimbo, Syncyclonema sp, Cardium pauperculum Meek, Tellina? Isonema Meek, Laternula sp, Parapholas sphenoideus White, Gyrodes depressa Meek, Gyrodes conradi Meek, Baculites yokoyamai Tokunaga and Shimizu, Scaphites corvensis Cobban, Bostrychoceras n. sp, Prionocyclus reesidei Sidwell, Prionocyclus germari (Reuss), Placenticeras sp., ","Ifossil":"Prionocyclus germari","collector":"Merewether and Cobban ","date":"12/6/1974","lat":"42.87165","lon":"-104.19027","reference":"Bull 1917-B,  PP 776"};markerLib['D9118'].marker = makeMarker(markerLib['D9118'].Dnum,markerLib['D9118'].lat,markerLib['D9118'].lon);pgermari_quadratusGroup.addLayer(markerLib['D9118'].marker);
markerLib['D12672'] = {"Dnum":"D12672","state":"NM","county":"Dona Ana","age":"Cretaceous","formation":"Mancos Shale, Gallup Sandstone ","member":"D-Cross Tongue Mbr.","stage":"Turonian","substage":"Upper","ageDate":"88.8","resume":"Prionocyclus reesidei, Prionocyclus germari (Reuss 1845), Mytiloides incertus, Lopha sannionus","Ifossil":"Prionocyclus germari","collector":"S.C.Hook, R.R. Cobban, W. A. Cobban ","date":"4/19/1977","lat":"32.5357","lon":"-106.5749","reference":"AMNH B267"};markerLib['D12672'].marker = makeMarker(markerLib['D12672'].Dnum,markerLib['D12672'].lat,markerLib['D12672'].lon);pgermari_quadratusGroup.addLayer(markerLib['D12672'].marker);
markerLib['D13114'] = {"Dnum":"D13114","state":"WY","county":"Johnson","age":"Cretaceous","formation":"Cody Shale, from large orange, silty concretions ","member":"","stage":"Turonian","substage":"Upper","ageDate":"88.8","resume":"Prionocyclus germari Ruess","Ifossil":"Prionocyclus germari","collector":"Cobban","date":"6/18/1990","lat":"44.225","lon":"-106.8","reference":""};markerLib['D13114'].marker = makeMarker(markerLib['D13114'].Dnum,markerLib['D13114'].lat,markerLib['D13114'].lon);pgermari_quadratusGroup.addLayer(markerLib['D13114'].marker);
markerLib['D14610'] = {"Dnum":"D14610","state":"NM","county":"Sierra","age":"Cretaceous","formation":"Mancos Shale Tongue between Gallup Sandstone #2 and #3, limy concretions near top.","member":"","stage":"Turonian","substage":"Upper","ageDate":"88.8","resume":"Prionocyclus germari","Ifossil":"Prionocyclus germari","collector":" S. C. Hook ","date":" May 22, 2007","lat":"33.13399","lon":"-107.20785","reference":""};markerLib['D14610'].marker = makeMarker(markerLib['D14610'].Dnum,markerLib['D14610'].lat,markerLib['D14610'].lon);pgermari_quadratusGroup.addLayer(markerLib['D14610'].marker);
markerLib['D14611'] = {"Dnum":"D14611","state":"NM","county":"Sierra","age":"Cretaceous","formation":"Gallup Sandstone #3, float in shale below, probably from near base. ","member":"","stage":"Turonian","substage":"Upper","ageDate":"88.8","resume":"Prionocyclus germari, Baculites yokoyamai","Ifossil":"Prionocyclus germari","collector":" S. C. Hook ","date":" May 22, 2007","lat":"33.13309","lon":"-107.20785","reference":""};markerLib['D14611'].marker = makeMarker(markerLib['D14611'].Dnum,markerLib['D14611'].lat,markerLib['D14611'].lon);pgermari_quadratusGroup.addLayer(markerLib['D14611'].marker);
markerLib['D2495'] = {"Dnum":"D2495","state":"NM","county":"Dona Ana","age":"Cretaceous","formation":"Mancos Shale","member":" D-Cross Tongue Mbr.","stage":"Turonian","substage":"Upper","ageDate":"89.8","resume":"Inoceramus cf. I. incertus Jimbo, Ostrea sp., Pecten (Syncyclonema) sp., Laternula sp., Cardium sp., Tellina sp., Baculites cf. B. besairiei Collignon, Bostrychoceras cf. B. elongatum (Whiteaves), Prionocyclus wyomingensis Meek, 1876, Prionocyclus germari (Reuss, 1845)","Ifossil":"Prionocyclus germari ","collector":"G. O. Bachman","date":"April 6-7, 1960","lat":"32.5509","lon":"-106.575","reference":" AMNH B267"};markerLib['D2495'].marker = makeMarker(markerLib['D2495'].Dnum,markerLib['D2495'].lat,markerLib['D2495'].lon);pgermari_quadratusGroup.addLayer(markerLib['D2495'].marker);
markerLib['D13351'] = {"Dnum":"D13351","state":"NM","county":"McKinley","age":"Cretaceous","formation":"Mancos Shale, from dark shale unit containing red ironestone concretions; about 152 ft below base of main Gallup Sandstone ","member":"","stage":"Turonian","substage":"Upper","ageDate":"88.8","resume":"Prionocyclus germari (Reuss)","Ifossil":"Prionocyclus germari ","collector":"W. A. Cobban ","date":"6/22/1992","lat":"35.54306","lon":"-108.19083","reference":""};markerLib['D13351'].marker = makeMarker(markerLib['D13351'].Dnum,markerLib['D13351'].lat,markerLib['D13351'].lon);pgermari_quadratusGroup.addLayer(markerLib['D13351'].marker);

shoreLib['pgermari_quadratus'].initInfo = 'D13351'
shoreLib['pgermari_quadratus'].markers=pgermari_quadratusGroup;