var sferronensisGroup = L.layerGroup();

markerLib['D30'] = {"Dnum":"D30","state":"CO","county":"Jackson","age":"Cretaceous","formation":"Carlile shale (Niobenton), basal Niobrara","member":"","stage":"Turonian","substage":"Middle","ageDate":"90","resume":"Scaphites ferronensis Cobban, Prionocyclus aff. P. wyomingensis Meek. Inoceramus dimidius White","Ifossil":"Scaphites ferronensis","collector":"T.A. Steven","date":"1954","lat":"40.90593","lon":"-106.30407","reference":""};markerLib['D30'].marker = makeMarker(markerLib['D30'].Dnum,markerLib['D30'].lat,markerLib['D30'].lon);sferronensisGroup.addLayer(markerLib['D30'].marker);
markerLib['D10466'] = {"Dnum":"D10466","state":"NM","county":"Socorro","age":"Cretaceous","formation":"Mancos Shale","member":", Juana Lopez Member about 5 ft above D10255","stage":"Turonian","substage":"Middle","ageDate":"89.5","resume":"Scaphites ferronensis","Ifossil":"Scaphites ferronensis","collector":"S. C. Hook and Tabet","date":"2/21/1978","lat":"34.08153","lon":"-106.65867","reference":""};markerLib['D10466'].marker = makeMarker(markerLib['D10466'].Dnum,markerLib['D10466'].lat,markerLib['D10466'].lon);sferronensisGroup.addLayer(markerLib['D10466'].marker);
markerLib['D10773'] = {"Dnum":"D10773","state":"NM","county":"San Miguel","age":"Cretaceous","formation":"Carlile Shale","member":"Juana Lopez Mbr. of ","stage":"Turonian","substage":"Middle","ageDate":"89.5","resume":"Scaphites ferronensis","Ifossil":"Scaphites ferronensis","collector":"Hook and Baltz","date":"6/6/1979","lat":"35.6839","lon":"-105.2318","reference":""};markerLib['D10773'].marker = makeMarker(markerLib['D10773'].Dnum,markerLib['D10773'].lat,markerLib['D10773'].lon);sferronensisGroup.addLayer(markerLib['D10773'].marker);
markerLib['D10950'] = {"Dnum":"D10950","state":"NM","county":"Valencia","age":"Cretaceous","formation":"D - Cross Shale, 35&apos; above base ","member":"","stage":"Turonian","substage":"Middle","ageDate":"89.5","resume":"Scaphites ferronensis, crinoid","Ifossil":"Scaphites ferronensis","collector":"C. M. Molenaar, S. C. Hook","date":"10/7/1979","lat":"34.74249","lon":"-107.91445","reference":""};markerLib['D10950'].marker = makeMarker(markerLib['D10950'].Dnum,markerLib['D10950'].lat,markerLib['D10950'].lon);sferronensisGroup.addLayer(markerLib['D10950'].marker);
markerLib['D11063'] = {"Dnum":"D11063","state":"NM","county":"Valencia","age":"Cretaceous","formation":"From limestone concretions 30 - 35&apos; above base of D - Cross Shale","member":"","stage":"Turonian","substage":"Middle","ageDate":"89.5","resume":"Scaphites ferronensis","Ifossil":"Scaphites ferronensis","collector":"Wright","date":"2/6/1980","lat":"34.7009","lon":"-107.88536","reference":""};markerLib['D11063'].marker = makeMarker(markerLib['D11063'].Dnum,markerLib['D11063'].lat,markerLib['D11063'].lon);sferronensisGroup.addLayer(markerLib['D11063'].marker);
markerLib['D11153'] = {"Dnum":"D11153","state":"NM","county":"Valencia","age":"Cretaceous","formation":"D - Cross Tongue, from orange - weathering concretion, 21&apos; above base ","member":"","stage":"Turonian","substage":"Middle","ageDate":"89.5","resume":"Scaphites ferronensis","Ifossil":"Scaphites ferronensis","collector":"Hook","date":"4/20/1980","lat":"34.70317","lon":"-107.93862","reference":""};markerLib['D11153'].marker = makeMarker(markerLib['D11153'].Dnum,markerLib['D11153'].lat,markerLib['D11153'].lon);sferronensisGroup.addLayer(markerLib['D11153'].marker);
markerLib['D12192'] = {"Dnum":"D12192","state":"CO","county":"Routt","age":"Cretaceous","formation":"","member":"Juana Lopez Mbr.","stage":"Turonian","substage":"Middle","ageDate":"89.5","resume":"Scaphites ferronensis","Ifossil":"Scaphites ferronensis","collector":"G. L. Snyder","date":"1965","lat":"40.73812","lon":"-106.91002","reference":""};markerLib['D12192'].marker = makeMarker(markerLib['D12192'].Dnum,markerLib['D12192'].lat,markerLib['D12192'].lon);sferronensisGroup.addLayer(markerLib['D12192'].marker);
markerLib['D15029'] = {"Dnum":"D15029","state":"NM","county":"Socorro","age":"Cretaceous","formation":"D-Cross Tongue of the Mancos Shale, upper 2&quot; thick calcarenite of the Juana Lopez Beds that is 4 ft 10 inches above D15028.","member":"","stage":"Turonian","substage":"Middle","ageDate":"90","resume":"Prionocyclus wyomingensis, Scaphites ferronensis, Inoceramus dimidius","Ifossil":"Scaphites ferronensis","collector":"S. C. Hook ","date":"3/16/2016","lat":"34.25984","lon":"-106.76449","reference":""};markerLib['D15029'].marker = makeMarker(markerLib['D15029'].Dnum,markerLib['D15029'].lat,markerLib['D15029'].lon);sferronensisGroup.addLayer(markerLib['D15029'].marker);
markerLib['D12554'] = {"Dnum":"D12554","state":"CO","county":"Rio Blanco","age":"Cretaceous","formation":"Uppermost 1 foot of Juana Lopez ","member":"","stage":"Turonian","substage":"Middle","ageDate":"90","resume":"Scaphites ferronensis , Prionocyclus wyomingensis","Ifossil":"Scaphites ferronensis ","collector":"E. A Merewether ","date":"7/29/1984","lat":"40.15522","lon":"-107.63171","reference":""};markerLib['D12554'].marker = makeMarker(markerLib['D12554'].Dnum,markerLib['D12554'].lat,markerLib['D12554'].lon);sferronensisGroup.addLayer(markerLib['D12554'].marker);

shoreLib['sferronensis'].initInfo = 'D12554'
shoreLib['sferronensis'].markers=sferronensisGroup;